[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python lesli45bot.py"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[deploy.variables]]
name = "PYTHONPATH"
value = "/app"
